# Generated by Django 5.2 on 2025-05-13 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_livro_autor_alter_livro_editora_delete_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivroUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemplares', models.PositiveIntegerField(default=1)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.livro')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.unidade')),
            ],
            options={
                'unique_together': {('livro', 'unidade')},
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='unidades',
            field=models.ManyToManyField(through='gestor.LivroUnidade', to='gestor.unidade'),
        ),
    ]
