# Generated by Django 5.2 on 2025-05-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_unidade_livrounidade_livro_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
