# Generated by Django 5.2 on 2025-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_tipo_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoobra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
