"""
Django settings for biblio.webapi project.
Generated by 'django-admin startproject' using Django 5.1.7.
"""

from pathlib import Path
import dj_database_url
import environ  # <-- lê o .env

# =========================
# Paths / Env
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega .env na raiz do projeto
env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")

# =========================
# Chaves / Flags
# =========================
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-h!ds_!gx+#axo!pggb^chklwxc&7)uq^jo6de48*b-l#q^0(51",
)

# Produção como padrão (pode sobrescrever no .env)
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=[
        "biblio-webapi.onrender.com",
        "localhost",
        "127.0.0.1",
        "bibliotecasconectadas.vercel.app",
    ],
)

# Em ambientes atrás de proxy (Render), garante https correto p/ CSRF/Secure cookies
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "https://biblio-webapi.onrender.com",
        "http://localhost:5173",
        "https://bibliotecasconectadas.vercel.app",
        "https://*.vercel.app",
    ],
)

# =========================
# Apps / Middleware
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # APIs
    "rest_framework",
    "drf_spectacular",
    "corsheaders",

    # app do projeto
    "src.gestor",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # deve ficar cedo na cadeia
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# =========================
# Database (Neon Postgres)
# =========================
# Ex.: DATABASE_URL=postgresql://user:pass@ep-...-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
_db_url = env("DATABASE_URL", default="")
if _db_url:
    DATABASES = {
        "default": dj_database_url.parse(
            _db_url,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # fallback seguro em dev se faltar .env
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =========================
# Password validation
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =========================
# I18N / TZ
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# =========================
# Static files
# =========================
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # útil pro Render coletar estáticos

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================
# DRF / Schemas / Renderers
# =========================
if DEBUG:
    REST_FRAMEWORK = {
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "DEFAULT_RENDERER_CLASSES": [
            "rest_framework.renderers.JSONRenderer",
            "rest_framework.renderers.BrowsableAPIRenderer",  # docs navegáveis no DEV
        ],
    }
else:
    REST_FRAMEWORK = {
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "DEFAULT_RENDERER_CLASSES": [
            "rest_framework.renderers.JSONRenderer",  # somente JSON em produção
        ],
    }

# 🔓 Permissões abertas temporariamente (sem autenticação real)
REST_FRAMEWORK["DEFAULT_PERMISSION_CLASSES"] = [
    "rest_framework.permissions.AllowAny"
]

# 🔧 Sem paginação global -> lista vira array puro (evita {"results":[...]})
REST_FRAMEWORK["DEFAULT_PAGINATION_CLASS"] = None

# =========================
# CORS
# =========================
# Estamos usando fetch sem sessão/cookies no frontend → não precisamos enviar credenciais
CORS_ALLOW_CREDENTIALS = False

# Declare explicitamente as origens permitidas (produção)
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:5173",
        "https://bibliotecasconectadas.vercel.app",
    ],
)

# Permitir previews *.vercel.app (além do domínio principal)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

# Cabeçalhos e métodos padrão (pode omitir se já ok no seu ambiente)
CORS_ALLOW_HEADERS = list(set([
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]))
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
